package npu

import chisel3._
import chisel3.util._

/**
 * QuasarScratchpadParams: configuration for one scratchpad bank.
 *
 * @param depth      number of addressable entries
 * @param width      bits per entry
 *
 * Architecture notes:
 *   - True dual-port: simultaneous read and write in the same cycle
 *   - Read port: synchronous — data valid one cycle after read_en
 *   - Write port: synchronous — data written on clock edge when write_en
 *   - In Phase 6 this module is replaced by a UCIe/TSV interface
 *     to the memory die. The port names and protocol stay identical
 *     so QuasarDoubleBuf and the DMA need no changes.
 *
 * CXL note (Phase 9):
 *   The write port will gain a CXL.mem slave interface so the host
 *   CPU can write tensor data directly into the scratchpad without
 *   going through the DMA. The read port remains array-facing.
 */
case class QuasarScratchpadParams(
                                   depth: Int = 1024,
                                   width: Int = 32
                                 ) {
  require(isPow2(depth), "Scratchpad depth must be power of 2")
  val addrBits = log2Ceil(depth)
}

/**
 * Separate read and write port bundles.
 * Keeping them distinct makes the dual-port nature explicit in the
 * type system — you can never accidentally connect a write port
 * where a read port is expected.
 */
class ScratchpadReadPort(p: QuasarScratchpadParams) extends Bundle {
  val en    = Input(Bool())
  val addr  = Input(UInt(p.addrBits.W))
  val data  = Output(UInt(p.width.W))
  val valid = Output(Bool())  // high one cycle after en
}

class ScratchpadWritePort(p: QuasarScratchpadParams) extends Bundle {
  val en   = Input(Bool())
  val addr = Input(UInt(p.addrBits.W))
  val data = Input(UInt(p.width.W))
}

/**
 * QuasarScratchpadIO: true dual-port interface.
 * Read and write ports are completely independent.
 */
class QuasarScratchpadIO(p: QuasarScratchpadParams) extends Bundle {
  val read  = new ScratchpadReadPort(p)
  val write = new ScratchpadWritePort(p)
}

/**
 * QuasarScratchpad: true dual-port synchronous SRAM.
 *
 * Read port behaviour:
 *   When read.en=true: latch addr, present data on read.data
 *   one cycle later with read.valid=true.
 *
 * Write port behaviour:
 *   When write.en=true: write data to addr on this clock edge.
 *
 * Both can happen simultaneously in the same cycle on different
 * addresses. If read.addr == write.addr in the same cycle,
 * behaviour is write-first (new data returned) — match what
 * SyncReadMem provides with the write-first semantic.
 *
 */
class QuasarScratchpad(val p: QuasarScratchpadParams = QuasarScratchpadParams())
  extends Module {
  val io = IO(new QuasarScratchpadIO(p))

  val mem = SyncReadMem(p.depth , UInt(p.width.W))

  val rdata = mem.read(io.read.addr , io.read.en)
  io.read.data := rdata
  io.read.valid := RegNext(io.read.en)

  when (io.write.en) {
    mem.write(io.write.addr , io.write.data)
  }
}

/**
 * QuasarDoubleBufIO: dual-port double buffer interface.
 *
 * array_port: read-only interface for the systolic array
 * dma_port:   write-only interface for the DMA engine
 * bank_sel:   selects which physical bank each port connects to
 *
 * CXL stub (Phase 9):
 *   A third port will be added here for CXL.mem host writes.
 *   The host CPU will write directly to the inactive bank while
 *   the array reads the active bank — three-way concurrent access.
 *
 * TAE stub (Phase 8):
 *   The dma_port address will be generated by the Tensor Access
 *   Engine rather than a simple sequential counter. The port
 *   interface stays identical — only the address source changes.
 */
class QuasarDoubleBufIO(p: QuasarScratchpadParams) extends Bundle {
  val array_port = new ScratchpadReadPort(p)   // array reads
  val dma_port   = new ScratchpadWritePort(p)  // DMA writes
  val bank_sel   = Input(Bool())
}

/**
 * QuasarDoubleBuf: two scratchpad banks with transparent bank selection.
 *
 * Routing table:
 *   bank_sel=0: array reads bank0, DMA writes bank1
 *   bank_sel=1: array reads bank1, DMA writes bank0
 *
 * The array and DMA always access different physical banks.
 * No arbitration needed — true simultaneous access.
 */
class QuasarDoubleBuf(val p: QuasarScratchpadParams = QuasarScratchpadParams())
  extends Module {
  val io = IO(new QuasarDoubleBufIO(p))

  val bank0 = Module(new QuasarScratchpad(p))
  val bank1 = Module(new QuasarScratchpad(p))

  when (!io.bank_sel) {
    bank0.io.read.en := io.array_port.en
    bank0.io.read.addr := io.array_port.addr
    bank0.io.write.en := false.B
    bank0.io.write.addr:= 0.U
    bank0.io.write.data:= 0.U

    bank1.io.read.en := false.B
    bank1.io.read.addr := 0.U
    bank1.io.write.en := io.dma_port.en
    bank1.io.write.addr := io.dma_port.addr
    bank1.io.write.data := io.dma_port.data
  } .otherwise {
    bank0.io.read.en := false.B
    bank0.io.read.addr := 0.U
    bank0.io.write.en := io.dma_port.en
    bank0.io.write.addr := io.dma_port.addr
    bank0.io.write.data := io.dma_port.data

    bank1.io.read.en := io.array_port.en
    bank1.io.read.addr := io.array_port.addr
    bank1.io.write.en := false.B
    bank1.io.write.addr := 0.U
    bank1.io.write.data := 0.U
  }

  io.array_port.data := Mux(io.bank_sel, bank1.io.read.data, bank0.io.read.data)
  io.array_port.valid := Mux(io.bank_sel, bank1.io.read.valid, bank0.io.read.valid)
}